### ISSUE TITLE
Move ganache into its own WebWorker

### ISSUE THREAD

**Issue by SamWilsn** [wallet-test-framework/framework#1]
Simulating a blockchain is a particularly CPU intensive task. If ganache runs on the main thread, it'll lock up the UI and cause other jank.

The [WebWorker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) API is how you spawn background tasks in the browser.

**Comment by Pandapip1** [comment]
You can also wrap it in an async function, which won't lock up the UI at the cost of remaining single thread.

**Comment by SamWilsn** [comment]
Unless ganache is going something fancy itself (and it may very well be), wrapping a CPU bound task in an `async` function won't actually improve responsiveness unless you also add yield points (like `setTimeout(0, ...)`).

For example, this'll lock up your tab, even though it's `async`:

```html
<!doctype html>
<html>
<head>
<script>async function foo() { while (true); }</script>
</head>
<body>
<input oninput="foo()">
</body>
</html>
```
