### ISSUE TITLE
Use the wallet specific glue instead of `wallet_addEthereumChain` to add the RPC provider

### ISSUE THREAD

**Issue by SamWilsn** [wallet-test-framework/framework#2]
`wallet_addEthereumChain` ~~is a non-standard endpoint and~~ isn't universally supported.

When running with wallet specific glue, we should just use that glue to add the RPC provider.

If we're running with the generic "tell the user what to do" glue, we can _try_ `wallet_addEthereumChain`, but have to fall back to just giving the user instructions on how to add the test chain.

**Comment by Pandapip1** [comment]
> wallet_addEthereumChain is a non-standard endpoint and isn't universally supported.

It's standardized, just stagnant: https://eips.ethereum.org/EIPS/eip-3085

**Comment by gaudren** [comment]
Implemented in f86bbe3b50bacd5228c0600598fb2e5f1a2c89aa
